### ISSUE TITLE
Items can't be created

### ISSUE THREAD

**Issue by Drental** [foundryvtt/black-flag#13]
When I try to create a Background I get an error message instead:
![image](https://user-images.githubusercontent.com/74384067/226176702-dd797305-8175-4f37-aaf8-4b7ae7cb4ea1.png)
```
Error: BlackFlagItem Model Validation Errors
[BlackFlagItem.system]: Model Validation Errors
[BackgroundTypeDataModel.description]: may not be undefined
[BackgroundTypeDataModel.color]: may not be undefined
[BackgroundTypeDataModel.equipment]: may not be undefined
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at BlackFlagItem.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseItem (commons.js:8590:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Item (foundry.js:19553:1)
    at new BlackFlagItem (item.mjs:1:16)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12525:15)
onError @ foundry.js:747
_preCreateDocumentArray @ foundry.js:12527
_createDocuments @ foundry.js:12459
create @ commons.js:6738
await in create (async)
createDocuments @ commons.js:6110
create @ commons.js:6233
callback @ foundry.js:13608
button.callback @ foundry.js:56516
submit @ foundry.js:56403
_onClickButton @ foundry.js:56332
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:59187 BlackFlagItem Model Validation Errors
[BlackFlagItem.system]: Model Validation Errors
[BackgroundTypeDataModel.description]: may not be undefined
[BackgroundTypeDataModel.color]: may not be undefined
[BackgroundTypeDataModel.equipment]: may not be undefined
fetch @ foundry.js:59187
notify @ foundry.js:59114
error @ foundry.js:59150
onError @ foundry.js:748
_preCreateDocumentArray @ foundry.js:12527
_createDocuments @ foundry.js:12459
create @ commons.js:6738
await in create (async)
createDocuments @ commons.js:6110
create @ commons.js:6233
callback @ foundry.js:13608
button.callback @ foundry.js:56516
submit @ foundry.js:56403
_onClickButton @ foundry.js:56332
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```
![image](https://user-images.githubusercontent.com/74384067/226176738-966ba225-55fd-4faf-b8aa-c4015a7e55b6.png)

I have no modules active and am of course using the most current version of the System. I can work through what I need by copying items and will look into it again later.

**Comment by Drental** [comment]
*testing in V10

**Comment by Drental** [comment]
it works in V11...

Okay, Mystery why this doesn't work solved. I can dev a new system on v11 just fine because stealing code from this project is all I want to do 🏴
